apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jen.fullname" . }}-api
  labels:
    app.kubernetes.io/name: jen
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: jen
spec:
  replicas: {{ .Values.apiGateway.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: jen
      app.kubernetes.io/component: api-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jen
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/part-of: jen
    spec:
      serviceAccountName: {{ .Values.serviceAccounts.names.api | default "default" }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          image: {{ .Values.apiGateway.image | quote }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port | default 8080 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
{{- toYaml .Values.apiGateway.resources | nindent 12 }}
          env:
            - name: JEN_ENVIRONMENT
              value: {{ .Values.global.environment | quote }}
            - name: JEN_PROVENANCE_SCHEMA
              value: {{ .Values.provenanceReporter.roCrate.schemaRef | default "" | quote }}
            - name: JEN_POLICIES_EGRESS_REF
              value: {{ .Values.policies.egressAllowlistRef | default "" | quote }}
            - name: JEN_POLICIES_VULN_REF
              value: {{ .Values.policies.vulnThresholdsRef | default "" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jen.fullname" . }}-api
  labels:
    app.kubernetes.io/name: jen
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: jen
spec:
  type: {{ .Values.apiGateway.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: jen
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.apiGateway.service.port | default 8080 }}
